language: go

go:
  - '1.11.x'
  - '1.12.x'
  - tip

go_import_path: github.com/gswly/go-dc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

before_install:
  - go mod download

script:
  - go test ./...